name: Build my gitbook and delploy to gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      MY_SECRET   : ${{secrets.AUTOBOOK01}}
      USER_NAME   : gboxgit
      USER_EMAIL  : lch.gbox@gmail.com
      BOOK_DIR    : book1

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - name: Build and Deploy 
      uses: onejar99/gitbook-build-publish-action@v1.0.0
